[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "bash"
file-types = ["sh", "bash"]
shebangs = ["bash"]
auto-format = false # Disable auto-formatting for this language if desired

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]
