# theme:
# https://github.com/alacritty/alacritty-theme
import = [
    # "~/.config/alacritty/themes/themes/coolnight.toml"
    "~/.config/alacritty/themes/themes/rose-pine-dawn.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
normal.family = "Hack Nerd Font Mono"

#regular
size = 14

#for video
# size = 35.0
