* Propals message

** flutter

Hi I am very interested in this project and would like to offer you my services for your project
I have more than 10 years experienced in making mobile app works
I completed more than 27 projects 

I will do this in less than 24 hours please message me

I will not disappoint you with my work and will give u a high quality work for sure


* flutter

Hi I am very interested in this project and would like to offer you my services for your project.

The following is what my proposals is: 
  1. The Clean Architecture
     Using library 'Getx' to bind Firebase's Stream.
     
  2. One module one Library. Unit test in each libraries.
  3. Using 'sentry' online services to monitor all exceptions.

I will not disappoint you with my work and will give u a high quality work for sure


* company
  https://www.kanzhun.com/job/1439366005.html
  [https://www.kanzhun.com/job/1439366005.html]

1、参与Android APP的需求分析； 2、负责Android APP的设计和开发工作，编写高质量的代码； 3、根据项目任务计划按时完成软件设计和实现； 4、持续的优化产品的用户体验，参与项目重点、难点技术攻坚。
  
本人具有多年工作经验，具备较强的业务管理能力，有很强的服务意识和学习能力，工作敬业，有责任心

  

As a Senior Mobile Software Developer at Credera,
I am a technical leader in a small team deployed to solve our client’s hardest problems.
I responsible to help the team design and estimate implementation tasks,
lead implementation work streams, and mentor junior team members.





















