# https://www.iszy.cc/2019/02/18/docker-v2ray/
version: "3"
services:
  v2ray:
    image: v2ray/official
    container_name: v2ray
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "31743:31743"
      #- "127.0.0.1:8889:8889"
    volumes:
      - ./v2ray:/etc/v2ray
      #- /etc/v2ray/v2ray.crt:/etc/v2ray/v2ray.crt
      #- /etc/v2ray/v2ray.key:/etc/v2ray/v2ray.key
