- id: geosite_notion.source
  tag: notion
  updateTime: 0
  disabled: false
  type: Http
  format: source
  path: data/rulesets/geosite_notion.json
  url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/notion.json
  count: 6
- id: geosite_stackexchange.source
  tag: stackexchange
  updateTime: 0
  disabled: false
  type: Http
  format: source
  path: data/rulesets/geosite_stackexchange.json
  url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/stackexchange.json
  count: 20
