* Code snippet
** hide keyboard layout  
  #+BEGIN_SRC dart
    FocusScope.of(context).requestFocus(FocusNode());
  #+END_SRC

* Tools
** melos
   Melos is a CLI tool used to help manage Dart projects with multiple packages.
   https://docs.page/invertase/melos
   
** dartdoc
   Use dartdoc to generate HTML documentaton for your Dart package.
   https://pub.dev/packages/dartdoc

*** Effective Dart: Documentation
   https://dart.dev/guides/language/effective-dart/documentation
  
** flutter_launcher_icons_maker
   A command-line tool which simplifies the task of updating your Flutter app's launcher icon. 
   https://pub.dev/packages/flutter_launcher_icons_maker

** Internationalizing Flutter apps
   https://flutter.dev/docs/development/accessibility-and-localization/internationalization
   
** intl_utils
   Dart package that creates a binding between your translations from .arb files and your Flutter app.
   It generates boilerplate code for official Dart Intl library and adds auto-complete for keys in Dart code.
   https://pub.dev/packages/intl_utils
   
** retrofit_generator   
   retrofit.dart is a type conversion dio client generator using source_gen and inspired by Chopper and Retrofit.
   https://mings.in/retrofit.dart/

* Plugins   
** mix
  https://pub.dev/packages/mix

  https://www.fluttermix.com/docs/core-concepts/attributes-and-utilities


** flutter_form_builder
   https://pub.dev/packages/flutter_form_builder
 
** flex_color_scheme  
   A Flutter package to make and use beautiful color scheme based themes.
   https://github.com/rydmike/flex_color_scheme

** permission_handler
   https://pub.dev/packages/permission_handler/changelog

   IMPORTANT: when updating to version 8.2.0
              make sure to also set the compileSdkVersion
              in the app/build.gradle file to 31.
  
* project templation 
** flutterGetFire
   Quick Starter for flutter using firebase & GetX 
   https://github.com/Addimohammedsaid/flutterGetFire
   keys: Firebase,Getx
  
* Projects   
** Flutter-Movie
   A Flutter movie app build with Fish-Redux and TMDB api.  
   https://github.com/o1298098/Flutter-Movie
  




   
