- id: ID_qwsktqnd
  name: singbox
  upload: 0
  download: 0
  total: 0
  expire: null
  updateTime: 1784280598301
  type: Http
  url: https://myclashes.top/sub?token=63a55a45114761972f3f6310abe6df74&sb
  website: ""
  path: data/subscribes/ID_qwsktqnd.json
  include: ""
  exclude: ""
  includeProtocol: ""
  excludeProtocol: direct|reject|selector|urltest|block|dns|shadowsocksr
  proxyPrefix: ""
  requestProxyMode: global
  customProxy: ""
  disabled: false
  inSecure: false
  requestMethod: GET
  requestTimeout: 15
  header:
    request:
      User-Agent: clash.meta/mihomo
    response: {}
  proxies:
    - id: ID_igz6mlw9
      tag: CF官方优选1
      type: vless
    - id: ID_7n78tj1n
      tag: CF官方优选2
      type: vless
    - id: ID_92h0o0o9
      tag: CF官方优选3
      type: vless
    - id: ID_sgmg3rgo
      tag: CF官方优选4
      type: vless
    - id: ID_b3zcbezb
      tag: CF官方优选5
      type: vless
    - id: ID_gk7ji7sd
      tag: CF官方优选6
      type: vless
    - id: ID_p24v5zrx
      tag: CF官方优选7
      type: vless
    - id: ID_14e0o2br
      tag: CF官方优选8
      type: vless
    - id: ID_t8ia5b4m
      tag: CF官方优选9
      type: vless
    - id: ID_dhhfy9am
      tag: CF官方优选10
      type: vless
  script: |-
    const onSubscribe = async (proxies, subscription) => {
      return { proxies, subscription }
    }
