#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    # Bootstrap Functions
    bootstrap_after = 'myspacevim#after'
    bootstrap_before = "myspacevim#before"
    # project manage
    project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '!node_packages/', '.projectile']

[[layers]]
  name = "colorscheme"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "cycle"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "fzf"

[[layers]]
  name = "lang#javascript"
  
[[layers]]
  name = "lang#typescript"  

[[layers]]
  name = "lang#python"

#[[layers]]
#  # https://spacevim.org/layers/edit/
#  name = 'edit'
#  # autosave_timeout = 300000
#  autosave_events = ['InsertLeave', 'TextChanged']

[[custom_plugins]]
  # https://github.com/907th/vim-auto-save
  name = "907th/vim-auto-save"

# [[custom_plugins]]
# name = "dart-lang/dart-vim-plugin"

# [[custom_plugins]]
# name = "thosakwe/vim-flutter"
