#!/usr/bin/env bash

current_hostname=$(scutil --get LocalHostName)

# echo "Current hostname: $current_hostname"

# djzhangs-Mac-mini

export MY_MAC_TYPE="unknown"
export MY_MAC_NAME="unknown"

if grep -qi "mac-mini" <<<"$current_hostname"; then
    export MY_MAC_TYPE="$MAC_TYPE_MINI"
    export MY_MAC_NAME="$MAC_NAME_MINI"
fi

if grep -qi "macbook-pro" <<<"$current_hostname"; then
    export MY_MAC_TYPE="$MAC_TYPE_PRO"
    export MY_MAC_NAME="$MAC_NAME_PRO"
fi

if grep -qi "mac-neo" <<<"$current_hostname"; then
    export MY_MAC_TYPE="$MAC_TYPE_NEO"
    export MY_MAC_NAME="$MAC_NAME_NEO"
fi

echo "Welcome $USER! Checking the current macos system type is $MY_MAC_TYPE, the name is $MY_MAC_NAME"
