- id: geosite_stackexchange.yaml
  name: stackexchange
  updateTime: 1741498949927
  disabled: false
  type: Http
  behavior: domain
  format: yaml
  path: data/rulesets/geosite_stackexchange.yaml
  url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/stackexchange.yaml
  count: 25
- id: geoip_bt.yaml
  name: bt
  updateTime: 1731063967836
  disabled: false
  type: Http
  behavior: ipcidr
  format: yaml
  path: data/rulesets/geoip_bt.yaml
  url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/bt.yaml
  count: 210
- id: geosite_java.yaml
  name: java
  updateTime: 1731755749314
  disabled: false
  type: Http
  behavior: domain
  format: yaml
  path: data/rulesets/geosite_java.yaml
  url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/java.yaml
  count: 3
- id: geosite_youtube.yaml
  name: youtube
  updateTime: 1735641600517
  disabled: false
  type: Http
  behavior: domain
  format: yaml
  path: data/rulesets/geosite_youtube.yaml
  url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo-lite/geosite/youtube.yaml
  count: 179
- id: geosite_github.yaml
  name: github
  updateTime: 1741504115837
  disabled: false
  type: Http
  behavior: domain
  format: yaml
  path: data/rulesets/geosite_github.yaml
  url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo-lite/geosite/github.yaml
  count: 29
- id: ID_m09x6hmc
  name: djzhang-sites
  updateTime: 1741522375133
  behavior: domain
  type: Manual
  format: yaml
  url: ""
  count: 2
  path: data/rulesets/djzhang-sites.yaml
  disabled: false
- id: ID_lge93orw
  name: developing-sites
  updateTime: 1741520862204
  behavior: classical
  type: Manual
  format: yaml
  url: ""
  count: 3
  path: data/rulesets/developing.yaml
  disabled: false
