(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade"  "https://marmalade-repo.org/packages/")

(development
   (depends-on "cask")
   (depends-on "elpy")
   (depends-on "exec-path-from-shell")
   (depends-on "pallet")
   (depends-on "bind-map")
)
