proxies:
  - name: CF官方优选1
    server: 104.19.34.45
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF官方优选2
    server: 104.19.51.105
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF官方优选3
    server: 172.67.77.98
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF官方优选4
    server: 104.17.186.195
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF官方优选5
    server: 104.17.145.61
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF官方优选6
    server: 104.18.33.77
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF官方优选7
    server: 108.162.198.31
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF官方优选8
    server: 104.18.33.192
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF官方优选9
    server: 104.17.125.11
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF官方优选10
    server: 108.162.198.42
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF官方优选11
    server: 108.162.198.93
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF官方优选12
    server: 104.17.212.172
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
