proxies:
  - name: wh1
    server: 162.159.153.209
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: wh2
    server: 162.159.153.160
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: wh3
    server: 162.159.153.163
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: visa.cn
    server: visa.cn
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: JP
    server: 154.19.187.141
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: JP 2
    server: 140.235.37.85
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: KR
    server: 158.247.198.196
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: JP 3
    server: 149.28.26.9
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 169ms 21.19MB/s
    server: 172.67.171.1
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 101.98ms 21.19MB/s
    server: 104.16.12.247
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 167.67ms 21.18MB/s
    server: 172.66.45.55
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 168.94ms 21.1MB/s
    server: 172.67.165.216
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 170.63ms 21.1MB/s
    server: 104.21.18.93
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 167.99ms 21.09MB/s
    server: 172.67.195.73
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 169.45ms 21.08MB/s
    server: 104.18.1.9
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 172.88ms 21.07MB/s
    server: 172.67.194.48
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 168.17ms 21.06MB/s
    server: 104.21.17.120
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 168.02ms 21.05MB/s
    server: 104.18.12.110
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 172.65ms 21.02MB/s
    server: 172.67.193.74
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 168.9ms 21.02MB/s
    server: 104.17.236.50
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 170.32ms 21.01MB/s
    server: 104.17.233.65
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 172.81ms 21.01MB/s
    server: 104.17.25.48
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 169.84ms 21MB/s
    server: 104.18.11.39
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 170.04ms 20.99MB/s
    server: 104.18.8.223
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 168.62ms 20.99MB/s
    server: 104.16.41.74
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 168.29ms 20.98MB/s
    server: 104.17.31.225
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 35.28ms 20.97MB/s
    server: 104.16.9.245
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 169.43ms 20.97MB/s
    server: 104.18.186.238
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 171.65ms 20.97MB/s
    server: 172.67.79.244
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 171.89ms 20.96MB/s
    server: 172.67.162.242
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
  - name: CF优选 171.09ms 20.95MB/s
    server: 172.67.199.26
    port: 443
    type: vless
    uuid: b2c43c2d-01fb-48ee-9a1c-8f1ee3227e10
    tls: true
    skip-cert-verify: false
    servername: myclashes.top
    client-fingerprint: chrome
    network: ws
    ws-opts:
      path: /
      headers:
        Host: myclashes.top
