# ttyS3's starship config with custom modules
# repo https://github.com/ttys3/starship-config
#
# ~/.config/starship.toml
# https://starship.rs/config/

# You can change default configuration file location with STARSHIP_CONFIG environment variable
# for example:
# export STARSHIP_CONFIG=~/.starship/config.toml

# default logs ~/.cache/starship/session_${STARSHIP_SESSION_KEY}.log
# make it custom:
# export STARSHIP_CACHE=~/.starship/cache

command_timeout=200

# Inserts a blank line between shell prompts
add_newline = false

# https://starship.rs/config/#default-prompt-format
format = """
$custom\
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$deno\
$golang\
$helm\
$nodejs\
$php\
$python\
$rust\
$memory_usage\
$aws\
$gcloud\
$env_var\
$lua\
$jobs\
$battery\
$time\
$cmd_duration\
$line_break\
$status\
$shell\
$character"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# [palettes.ccswe_dark]
# color_bg1 = "#336699"
# color_bg2 = "#2f5783"
# color_bg3 = "#294262"
# color_bg4 = "#232f44"
# color_bg5 = "#1d2230"
#
# color_blue = "#769ff0"
# color_gray = "#999999"
# color_red = "#eb4d28"
# color_white = "#f2f2f2"

[character]
error_symbol = "[❯](bold color_red)"
success_symbol = "[❯](bold color_blue)"

# [directory]
# read_only = " "
# truncation_length = 8
# truncate_to_repo = false
# truncation_symbol = "…/"

[directory]
read_only = " "
truncation_length = 1
home_symbol = "~"
#style = "bold orange"

[kubernetes]
# The namespace needs to be set in the kubeconfig file
# If the $KUBECONFIG env var is set the module will use that if
# not it will use the ~/.kube/config
disabled = true
# https://starship.rs/advanced-config/#style-strings
style = "purple bold"
format = '[$symbol$context( \($namespace\))]($style) in '

[time]
disabled = true
use_12hr = false
format = '🕙[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "local"
time_range = "09:00:00-19:10:00"

[status]
symbol = "🔴 "
disabled = false

[git_commit]
tag_disabled = false

# https://github.com/starship/starship/discussions/1252#discussioncomment-822676
# show os icon, thanks https://www.nerdfonts.com/cheat-sheet
#                 
[custom.os-icon]
disabled = false
command = "os-icon"
style = "bold blue"
format = "[$symbol($output  )]($style)"
symbol = ""
when = "true"
shell = ["bash", "--noprofile", "--norc"]

[custom.vpn-icon]
disabled = true
command = "curl -Ssf -H 'accept: text/plain' http://127.0.0.1:8084/api/vpn/status/icon"
style = "bold green"
format = "[$symbol($output)]($style)"
symbol = "VPN"
when = "true"
shell = ["bash", "--noprofile", "--norc"]

# https://github.com/starship/starship/discussions/1252#discussioncomment-838901
[custom.git_remote_url]
description = 'Remote git repository'
when = 'git rev-parse --is-inside-work-tree'
command = """
GIT_REMOTE=$(command git remote get-url origin 2> /dev/null)
if [[ -z "$GIT_REMOTE" ]]; then
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
fi
GIT_REMOTE_URL=$(echo $GIT_REMOTE | sed -E 's/^https?:\\/\\/(.+@)?//; s/\\.git$//;  s/\\.git$//; s/.+@(.+):([[:digit:]]+)\\/(.+)$/\\1\\/\\3/; s/.+@(.+):(.+)$/\\1\\/\\2/; s/\\/$//')
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ -n "$GIT_REMOTE" ]]; then
    GIT_REMOTE_SYMBOL=" "
else
    GIT_REMOTE_SYMBOL=" "
fi

GIT_USERNAME_USED=$(command git config --get user.name 2> /dev/null)

echo "$GIT_REMOTE_SYMBOL$GIT_USERNAME_USED@$GIT_REMOTE_URL"
"""
# Default format is according to the segmented-brackets preset (https://github.com/starship/starship/pull/2747)
format = '\[[$output]($style)\]'
# If you prefer the default Starship style, use the following
# format = "at [$output]($style)"
shell = ["bash", "--noprofile", "--norc"]
style = 'blue'

# symbol presets
# https://starship.rs/presets/#nerd-font-symbols
[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

# [directory]
# read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = "ﯣ "

[lua]
symbol = " "

[nodejs]
style = "bg:color_bg4 fg:#5FA04E"
format = '[$symbol($version)]($style)'
symbol = " "

