-- custom shortcuts on the uPDF app

hs.hotkey.bind({ "Cmd" }, "7", function()
    hs.timer.doAfter(0.5, function()
        hs.eventtap.keyStroke({ "Cmd", "Ctrl" }, "7")
        -- hs.notify.new({ title = "toggle 'UPDF' page view type", informativeText = "run it sucessfully" }):send()
    end)
end)

hs.hotkey.bind({ "Cmd" }, "8", function()
    hs.timer.doAfter(0.5, function()
        hs.eventtap.keyStroke({ "Cmd", "Ctrl" }, "8")
        -- hs.notify.new({ title = "toggle 'UPDF' page view type", informativeText = "run it sucessfully" }):send()
    end)
end)

hs.hotkey.bind({ "Cmd" }, "9", function()
    hs.timer.doAfter(0.5, function()
        hs.eventtap.keyStroke({ "Cmd", "Ctrl" }, "9")
        -- hs.notify.new({ title = "toggle 'UPDF' page view type", informativeText = "run it sucessfully" }):send()
    end)
end)

hs.hotkey.bind({ "Cmd" }, "0", function()
    hs.timer.doAfter(0.5, function()
        hs.eventtap.keyStroke({ "Cmd", "Ctrl" }, "0")
        -- hs.notify.new({ title = "toggle 'UPDF' page view type", informativeText = "run it sucessfully" }):send()
    end)
end)

hs.hotkey.bind({ "Cmd" }, "f", function()
    hs.timer.doAfter(0.5, function()
        hs.eventtap.keyStroke({ "fn" }, "f")
        -- hs.notify.new({ title = "toggle 'UPDF' page view type", informativeText = "run it sucessfully" }):send()
    end)
end)
