- id: ID_an5h55ca
  name: singbox
  useInternal: false
  upload: 0
  download: 0
  total: 0
  expire: null
  updateTime: 1786699837703
  type: Http
  url: https://myclashes.top/sub?token=63a55a45114761972f3f6310abe6df74&clash
  website: ""
  path: data/subscribes/ID_an5h55ca.yaml
  include: ""
  exclude: ""
  includeProtocol: ""
  excludeProtocol: ""
  proxyPrefix: ""
  requestProxyMode: global
  customProxy: ""
  disabled: false
  inSecure: false
  requestMethod: GET
  requestTimeout: 15
  header:
    request:
      User-Agent: clash.meta/mihomo
    response: {}
  script: |-
    const onSubscribe = async (proxies, subscription) => {
      return { proxies, subscription }
    }
  proxies:
    - id: ID_uwjz3sdf
      name: CF官方优选1
      type: vless
    - id: ID_m4w4la5g
      name: CF官方优选2
      type: vless
    - id: ID_g79yzfga
      name: CF官方优选3
      type: vless
    - id: ID_37yh6p2z
      name: CF官方优选4
      type: vless
    - id: ID_ftiaop9s
      name: CF官方优选5
      type: vless
    - id: ID_0y4qahle
      name: CF官方优选6
      type: vless
    - id: ID_h73njchy
      name: CF官方优选7
      type: vless
    - id: ID_gnov9nso
      name: CF官方优选8
      type: vless
    - id: ID_vpsropdw
      name: CF官方优选9
      type: vless
    - id: ID_ud0orfx3
      name: CF官方优选10
      type: vless
    - id: ID_e6hcruzd
      name: CF官方优选11
      type: vless
    - id: ID_xmb8qd4k
      name: CF官方优选12
      type: vless
