hs.hotkey.bind(GameHotkeyMods, "C", Play_Assassins_Creed_Mirage)
hs.hotkey.bind(GameHotkeyMods, "D", Play_Horizon_Zero_Dawn_Remastered)
-- hs.hotkey.bind(GameHotkeyMods, "D", Play_Call_of_Duty_Modern_Warfare_Remastered)
hs.hotkey.bind(GameHotkeyMods, "O", Play_Assassins_Creed_Origins)
hs.hotkey.bind(GameHotkeyMods, "G", Play_Grand_Theft_Auto_V)
hs.hotkey.bind(GameHotkeyMods, "H", Play_Silent_Hill_2)
hs.hotkey.bind(GameHotkeyMods, "U", Play_UNCHARTED_LoT_Collection)
hs.hotkey.bind(GameHotkeyMods, "R", Play_Red_Dead_Redemption)
hs.hotkey.bind(GameHotkeyMods, "L", Play_The_Last_of_Us_Part_II)
hs.hotkey.bind(GameHotkeyMods, "M", Play_Mafia_II_Definitive_Edition)
hs.hotkey.bind(GameHotkeyMods, "N", Play_Need_for_Speed_Heat)
hs.hotkey.bind(GameHotkeyMods, "S", Play_Marvel_Spider_Man_Remastered)
hs.hotkey.bind(GameHotkeyMods, "W", Play_The_Witcher_3_Wild_Hunt)
