#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    # colorscheme = "onedark"
    # colorscheme = "molokai"
    colorscheme_bg = "dark"
    background = "dark"
    guifont = "SauceCodePro Nerd Font Mono:h11"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false 
   # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # Enable Vim compatible mode, avoid changing origin Vim key bindings
    vimcompatible = true
    # my space
    bootstrap_before = "myspacevim#init"
    # Side Tree
    # filemanager = 'nerdtree' 
    # Project
    project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/','.next','node_modules','ios','android','build','production-cloud','production-server']

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"


[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "colorscheme"

[[layers]]
name = "unite"

[[layers]]
name = "tmux"
tmux_navigator_modifier = "alt"

# [[layers]]
  # name = "lang#javascript"
  # enable_flow_syntax = false

# [[layers]]
# /Users/djzhang/.cache/vimfiles/repos/github.com/mhartington/nvim-typescript/install.sh
# name = "lang#typescript"

[[custom_plugins]]
name = "907th/vim-auto-save"

[[custom_plugins]]
name = "Quramy/tsuquyomi"

[[custom_plugins]]
name = "leafgarland/typescript-vim"

[[custom_plugins]]
name = "leshill/vim-json"
