  aria2:
    container_name: Aria2
    image: abcminiuser/docker-aria2-with-webui:latest
    network_mode: "bridge"
    ports:
      - 6800:6800
      - 6880:80
    volumes:
      - /home/deploy/data/complete:/data
      - /home/deploy/data/Aria2:/conf
    environment:
      - PGID=100
      - PUID=1001
    restart: unless-stopped